# Install Dependecies
echo "START: Install python packages"
pip3 install -r requirements.txt
echo "END: Install python packages"
echo "============================="
# Setup Environment Variables
echo "START: Setting up environment variables"
echo on
export DATABASE_NAME=casting_agency
export DATABASE_URL=postgres://postgres@localhost:5432/casting_agency?gssencmode=disable
export APP_SECRET_KEY=some-secret-key
export AUTH0_API_AUDIENCE=casting-agency-api
export AUTH0_CLIENT_ID=IrrwsvDC9WQZ404zksQ0ALJsbKGZwX4m
export AUTH0_CLIENT_SECRET=RKGin-TP7Ys4qGdg-8zO9DYT1UQi-XiZ9drQhiCSzKCza_eOC4SWwb1S2NW57taJ
export AUTH0_DOMAIN=ashishp-dev.us.auth0.com
export AUTH0_CALLBACK_URL=http://localhost:5000/api/auth/callback
export TEST_DATABASE_URL=postgres://postgres@localhost:5432/test_casting_agency?gssencmode=disable
export TEST_ASSISTANT_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkhadkctNmducWtiRE1jTnE3UUZycCJ9.eyJpc3MiOiJodHRwczovL2FzaGlzaHAtZGV2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjMwZTA4NmQ1MzA3YTAwM2QyOTI4YWQiLCJhdWQiOlsiY2FzdGluZy1hZ2VuY3ktYXBpIiwiaHR0cHM6Ly9hc2hpc2hwLWRldi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNTk3NTMzMjE1LCJleHAiOjE1OTc2MTk2MTUsImF6cCI6IklycndzdkRDOVdRWjQwNHprc1EwQUxKc2JLR1p3WDRtIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbInJlYWQ6YWN0b3JzIiwicmVhZDptb3ZpZXMiXX0.XxMkccK_ZNIOESBl3KQTInJ--YcouJq1jvCt6QUV3LOB32oWHt3dHyHcEWBJ-yL66zaF1od6YUOtc5V2pdynVXwFciYaKPH0OOlZ31A58AFMaUZsIiRNnNxXJeVcCLmPbhTl5q9_5da7mcEc1hHfvPeePx8jvQKte-XdUcsQDPp3a4d1W24piE6k2X_VwfZYSC2AExPNzfm8Uo7f_Nz55R5E77_SgaXNatlWSM6-8L2xEFZmGW2oQrK1nYkfYhizC6vAynQ-QyzoaHmszuKRz2MYIzir_WdtHkF9d50LdpaCEbedLM5pS_UZ4JJCWMoXoDKn-vXey9ywoFBIwsp-1g
export TEST_DIRECTOR_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkhadkctNmducWtiRE1jTnE3UUZycCJ9.eyJpc3MiOiJodHRwczovL2FzaGlzaHAtZGV2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjMwZTBiYzNhY2QwZTAwM2ExOWU5ZWEiLCJhdWQiOlsiY2FzdGluZy1hZ2VuY3ktYXBpIiwiaHR0cHM6Ly9hc2hpc2hwLWRldi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNTk3NTM0OTU4LCJleHAiOjE1OTc2MjEzNTgsImF6cCI6IklycndzdkRDOVdRWjQwNHprc1EwQUxKc2JLR1p3WDRtIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbImNyZWF0ZTphY3RvcnMiLCJkZWxldGU6YWN0b3JzIiwicmVhZDphY3RvcnMiLCJyZWFkOm1vdmllcyIsInVwZGF0ZTphY3RvcnMiLCJ1cGRhdGU6bW92aWVzIl19.wAK6_T4joSWpmEzja4AIANfISTTWE-dOHDHgOCiIIfatAvWkAVwObLtFgimVCdb5EhFwuxi96qzQ2KT8IRYH-As1QHqtYQGU_TCdGbympzhpjP9qdCRoTZa9NdswvXdCScIu8Tq_xH_wmeXnPZXtYG2rYId3S2T0yx-xQHNHXkzNWmMNuYE81gsNtmJ_3AGwPezjviO_KFB-KBOxRcek9ueDIQ43t6-eWJKc9WvMvIZ84y9onMk5cqQYW5fTQ1Ow7F1hHzDA5hPmlL5Nlb0ZiXdl7RC491-FD9MC6WLhRRTLkbzFVkXv_-wQakE6tfFDZFBwHoUISL-hDTbvdffkCQ
export TEST_PRODUCTER_TOKEN=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkhadkctNmducWtiRE1jTnE3UUZycCJ9.eyJpc3MiOiJodHRwczovL2FzaGlzaHAtZGV2LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjMwZTBlOWQyZjFjZDAwMzdlZmNhNWEiLCJhdWQiOlsiY2FzdGluZy1hZ2VuY3ktYXBpIiwiaHR0cHM6Ly9hc2hpc2hwLWRldi51cy5hdXRoMC5jb20vdXNlcmluZm8iXSwiaWF0IjoxNTk3NTM0OTkyLCJleHAiOjE1OTc2MjEzOTIsImF6cCI6IklycndzdkRDOVdRWjQwNHprc1EwQUxKc2JLR1p3WDRtIiwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInBlcm1pc3Npb25zIjpbImNyZWF0ZTphY3RvcnMiLCJjcmVhdGU6bW92aWVzIiwiZGVsZXRlOmFjdG9ycyIsImRlbGV0ZTptb3ZpZXMiLCJyZWFkOmFjdG9ycyIsInJlYWQ6bW92aWVzIiwidXBkYXRlOmFjdG9ycyIsInVwZGF0ZTptb3ZpZXMiXX0.xG8MAiSuUtRUvbX9iJKME8RzFbbNIBsUjIQeL-RUsH_qE6F9mXSe1syPVaz21GJlnt7liWgHB4flHIw8-fPEXXWyK1VEVFoES8TXa09-qGTPkRAdXwobCmzbZO7cS-xQa06KZE4FKAGio2caxlev8R9Migr8Aj-vh9k7NA_BmT0vxr-3uVNiUBQ8r7e5fHTTDNvUkhLI7xGY7qNHGrRXgBzaddxHePpyA-_YavL0xUKjXr83YYHZxryqv17UBikj7EKtB-_UrpXsBNy4GjRncbcBIsJjsvEutEyXA9o-UJHddvhXgNBTWdw3i6zIY0PYB8S4W3PHUyeRHvLZZx7kPg
echo "END: Setting up environment variables"
echo "============================="

# Execute Test cases
echo "START: Running Unit Tests"
pytest
echo "END: Running Unit Tests"
echo "============================="



